spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: ${secrets.datasource.url}
    #    url: ${secrets.datasource.url}
    username: ${secrets.datasource.username}
    password: ${secrets.datasource.password}
#    password: ${secrets.datasource.password}
  # Mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${secrets.mail.username}
    password: ${secrets.mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port:
    8082
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    session:
      tracking-modes: cookie
    multipart:
      enabled: true
      max-file-size: 2MB

# TODO : 이미지 저장 경로 /upload 왼쪽 경로는 각자 경로를 적어줘야 한다.
file:
  path: ${secrets.file.path}