spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: mozip
    password: mozip1234
  mvc:
    view: # JSP 설정
      prefix: /WEB-INF/views/
      suffix: .jsp

server:
  port:
    8082
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    jsp:
      init-parameters:
        developmente: true
