spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: mozip
    password: mozip1234

server:
  port:
    8084
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    session:
      tracking-modes: cookie