spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
    # url: ${secrets.datasource.url}
    username: mozip
    password: mozip1234
  # password: ${secrets.datasource.password}
  # Mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: chlwodud19970327@gmail.com
    password: wpiavganhaqabkem
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port:
    8082
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    session:
      tracking-modes: cookie
    multipart:
      enabled: true
      max-file-size: 2MB

# TODO : 이미지 저장 경로 /upload 왼쪽 경로는 각자 경로를 적어줘야 한다.
file:
  path: /Users/yoonji/git/pj-img/