spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${secrets.datasource.url}
    username: ${secrets.datasource.username}
    password: ${secrets.datasource.password}
  # Mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${secrets.mail.username}
    password: ${secrets.mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  #  Kakao 로그인 API
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: f37021dae16ea2b1778275828eb7ee08
            client-secret: 30QjrDqVeK0txHxzM9T9knBmjO55g9n2
            client-name: kakao-login
            scope:
              - profile_nickname
              - profile_image
            authorization-grant-type: authorizaion_code
            redirect-uri: http://localhost:8082/login/oauth2/code/kakao
            client-authentication-method: POST
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
server:
  port:
    8082
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    session:
      tracking-modes: cookie
    multipart:
      enabled: true
      max-file-size: 2MB

# TODO : 이미지 저장 경로 /upload 왼쪽 경로는 각자 경로를 적어줘야 한다.
file:
  path: ${secrets.file.path}