spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${secrets.datasource.url}
    username: ${secrets.datasource.username}
    password: ${secrets.datasource.password}
  # Mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${secrets.mail.username}
    password: ${secrets.mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  #  Kakao 로그인 API
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${secrets.registration.kakao.client-id}
            client-secret: ${secrets.registration.kakao.client-secret}
            scope:
              - profile_nickname
              - profile_image
              - account_email
            authorization-grant-type: authorization_code
            redirect-uri: ${secrets.registration.kakao.redirect-uri}
            client-name: Kakao
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  thymeleaf:
    suffix: .html
    prefix: classpath:/templates/
server:
  port:
    8082
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    session:
      tracking-modes: cookie
    multipart:
      enabled: true
      max-file-size: 2MB

# TODO : 이미지 저장 경로 /upload 왼쪽 경로는 각자 경로를 적어줘야 한다.
file:
  path: ${secrets.file.path}

# Mybatis 로그
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 쿼리를 콘솔에 출력

logging:
  level:
    root: INFO # 기본 로깅 레벨 설정
    com.mozip: DEBUG # 프로젝트 패키지 로깅 레벨 설정
    org.apache.ibatis.logging.stdout.StdOutImpl: DEBUG # MyBatis 로깅 레벨 설정

